/* This file is auto-generated by front-end/scripts/generate-api-client.mjs. Do not edit manually. */

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type EmptyObject = Record<never, never>;

export interface RequestOtpDto {
  phone: string;
}
export interface VerifyOtpDto {
  phone: string;
  code: string;
}
export interface RefreshTokenDto {
  refreshToken: string;
}
export interface UpdateProfileDto {
  fullName?: string;
  email?: string;
  preferredArea?: string;
}
export interface CreateBookingDto {
  listingId: string;
  date: string;
  timeSlot: string;
  note?: string;
}
export interface RescheduleBookingDto {
  date: string;
  timeSlot: string;
}
export interface UpdateAppStateDto {
  payload: Record<string, unknown>;
}
export interface CreatePushSubscriptionDto {
  endpoint: string;
  keys: Record<string, unknown>;
}
export interface CreateConversationDto {
  listingId?: string;
  ownerId: string;
}
export interface CreateMessageDto {
  body: string;
}
export interface CreateDepositDto {
  listingId: string;
  amount: number;
  provider?: string;
}
export interface PaymentWebhookDto {
  reference: string;
  status: "PENDING" | "PROCESSING" | "PAID" | "FAILED" | "REFUNDED";
  amount?: number;
  provider?: string;
  eventId?: string;
}
export interface CreateContractDto {
  listingId: string;
  fileUrl?: string;
}
export interface CreateOwnerListingDto {
  title: string;
  description: string;
  address: string;
  district: string;
  city?: string;
  price: number;
  deposit?: number;
  area: number;
  bedrooms?: number;
  bathrooms?: number;
  floor?: string;
  electricityFee?: string;
  waterFee?: string;
  parkingFee?: string;
  petAllowed?: boolean;
  amenities?: Array<string>;
}
export interface UpdateOwnerListingDto {
  title?: string;
  description?: string;
  address?: string;
  district?: string;
  city?: string;
  price?: number;
  deposit?: number;
  area?: number;
  bedrooms?: number;
  bathrooms?: number;
  floor?: string;
  electricityFee?: string;
  waterFee?: string;
  parkingFee?: string;
  petAllowed?: boolean;
  amenities?: Array<string>;
}
export interface AddListingImageDto {
  url: string;
  alt?: string;
  sortOrder?: number;
}
export interface CreateImageUploadIntentDto {
  filename: string;
  contentType: string;
  sizeBytes: number;
  alt?: string;
  sortOrder?: number;
}
export interface ReviewListingDto {
  status: "DRAFT" | "PENDING_REVIEW" | "PUBLISHED" | "PAUSED" | "REJECTED";
  note?: string;
}
export interface UpdateDisputeDto {
  status: "OPEN" | "IN_REVIEW" | "RESOLVED" | "REJECTED";
  note?: string;
}

export type ApiMethod = "GET" | "POST" | "PATCH" | "DELETE";

export interface ApiOperations {
  "GET /health": {
    method: "GET";
    path: "/health";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: false;
  };
  "GET /health/ready": {
    method: "GET";
    path: "/health/ready";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: false;
  };
  "POST /auth/otp/request": {
    method: "POST";
    path: "/auth/otp/request";
    requestBody: RequestOtpDto;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: false;
  };
  "POST /auth/otp/verify": {
    method: "POST";
    path: "/auth/otp/verify";
    requestBody: VerifyOtpDto;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: false;
  };
  "POST /auth/logout": {
    method: "POST";
    path: "/auth/logout";
    requestBody: RefreshTokenDto | undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: false;
  };
  "POST /auth/refresh": {
    method: "POST";
    path: "/auth/refresh";
    requestBody: RefreshTokenDto;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: false;
  };
  "GET /me": {
    method: "GET";
    path: "/me";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /users/me/profile": {
    method: "GET";
    path: "/users/me/profile";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "PATCH /users/me/profile": {
    method: "PATCH";
    path: "/users/me/profile";
    requestBody: UpdateProfileDto;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /listings": {
    method: "GET";
    path: "/listings";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: {
    district?: string;
    keyword?: string;
    minPrice?: number;
    maxPrice?: number;
    minArea?: number;
    petAllowed?: boolean;
    page?: number;
    limit?: number;
  };
    response: unknown;
    auth: false;
  };
  "GET /listings/{id}": {
    method: "GET";
    path: "/listings/{id}";
    requestBody: undefined;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: false;
  };
  "GET /listings/{id}/availability": {
    method: "GET";
    path: "/listings/{id}/availability";
    requestBody: undefined;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: false;
  };
  "GET /me/bookings": {
    method: "GET";
    path: "/me/bookings";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "POST /bookings": {
    method: "POST";
    path: "/bookings";
    requestBody: CreateBookingDto;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "PATCH /bookings/{id}/reschedule": {
    method: "PATCH";
    path: "/bookings/{id}/reschedule";
    requestBody: RescheduleBookingDto;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "PATCH /bookings/{id}/cancel": {
    method: "PATCH";
    path: "/bookings/{id}/cancel";
    requestBody: undefined;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /me/app-state": {
    method: "GET";
    path: "/me/app-state";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "PATCH /me/app-state": {
    method: "PATCH";
    path: "/me/app-state";
    requestBody: UpdateAppStateDto;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "POST /notifications/push-subscriptions": {
    method: "POST";
    path: "/notifications/push-subscriptions";
    requestBody: CreatePushSubscriptionDto;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /me/notifications": {
    method: "GET";
    path: "/me/notifications";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "PATCH /me/notifications/{id}/read": {
    method: "PATCH";
    path: "/me/notifications/{id}/read";
    requestBody: undefined;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /me/saved-listings": {
    method: "GET";
    path: "/me/saved-listings";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "POST /me/saved-listings/{listingId}": {
    method: "POST";
    path: "/me/saved-listings/{listingId}";
    requestBody: undefined;
    pathParams: {
    listingId: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "DELETE /me/saved-listings/{listingId}": {
    method: "DELETE";
    path: "/me/saved-listings/{listingId}";
    requestBody: undefined;
    pathParams: {
    listingId: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /conversations": {
    method: "GET";
    path: "/conversations";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "POST /conversations": {
    method: "POST";
    path: "/conversations";
    requestBody: CreateConversationDto;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /conversations/{id}/messages": {
    method: "GET";
    path: "/conversations/{id}/messages";
    requestBody: undefined;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "POST /conversations/{id}/messages": {
    method: "POST";
    path: "/conversations/{id}/messages";
    requestBody: CreateMessageDto;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "PATCH /conversations/{id}/read": {
    method: "PATCH";
    path: "/conversations/{id}/read";
    requestBody: undefined;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "POST /payments/deposits": {
    method: "POST";
    path: "/payments/deposits";
    requestBody: CreateDepositDto;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /payments/{id}": {
    method: "GET";
    path: "/payments/{id}";
    requestBody: undefined;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "POST /payments/webhook": {
    method: "POST";
    path: "/payments/webhook";
    requestBody: PaymentWebhookDto;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: false;
  };
  "POST /contracts": {
    method: "POST";
    path: "/contracts";
    requestBody: CreateContractDto;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /contracts/{id}": {
    method: "GET";
    path: "/contracts/{id}";
    requestBody: undefined;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /owner/dashboard": {
    method: "GET";
    path: "/owner/dashboard";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /owner/listings": {
    method: "GET";
    path: "/owner/listings";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "POST /owner/listings": {
    method: "POST";
    path: "/owner/listings";
    requestBody: CreateOwnerListingDto;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "PATCH /owner/listings/{id}": {
    method: "PATCH";
    path: "/owner/listings/{id}";
    requestBody: UpdateOwnerListingDto;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "POST /owner/listings/{id}/images": {
    method: "POST";
    path: "/owner/listings/{id}/images";
    requestBody: AddListingImageDto;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "POST /owner/listings/{id}/images/upload-intent": {
    method: "POST";
    path: "/owner/listings/{id}/images/upload-intent";
    requestBody: CreateImageUploadIntentDto;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /owner/bookings": {
    method: "GET";
    path: "/owner/bookings";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "PATCH /owner/bookings/{id}/confirm": {
    method: "PATCH";
    path: "/owner/bookings/{id}/confirm";
    requestBody: undefined;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /admin/metrics": {
    method: "GET";
    path: "/admin/metrics";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /admin/verifications": {
    method: "GET";
    path: "/admin/verifications";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /admin/listings": {
    method: "GET";
    path: "/admin/listings";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "POST /admin/verifications/{id}/approve": {
    method: "POST";
    path: "/admin/verifications/{id}/approve";
    requestBody: undefined;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "POST /admin/verifications/{id}/request-more": {
    method: "POST";
    path: "/admin/verifications/{id}/request-more";
    requestBody: undefined;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "POST /admin/listings/{id}/review": {
    method: "POST";
    path: "/admin/listings/{id}/review";
    requestBody: ReviewListingDto;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /admin/disputes": {
    method: "GET";
    path: "/admin/disputes";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "PATCH /admin/disputes/{id}": {
    method: "PATCH";
    path: "/admin/disputes/{id}";
    requestBody: UpdateDisputeDto;
    pathParams: {
    id: string;
  };
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
  "GET /admin/audit-logs": {
    method: "GET";
    path: "/admin/audit-logs";
    requestBody: undefined;
    pathParams: EmptyObject;
    query: EmptyObject;
    response: unknown;
    auth: true;
  };
}

export type ApiOperationKey = keyof ApiOperations;
export type ApiOperationKeyByMethod<M extends ApiMethod> = {
  [K in ApiOperationKey]: ApiOperations[K]["method"] extends M ? K : never;
}[ApiOperationKey];
export type ApiRequestBody<K extends ApiOperationKey> = ApiOperations[K]["requestBody"];
export type ApiPathParams<K extends ApiOperationKey> = ApiOperations[K]["pathParams"];
export type ApiQuery<K extends ApiOperationKey> = ApiOperations[K]["query"];
export type ApiResponse<K extends ApiOperationKey> = ApiOperations[K]["response"];

export const apiOperations = {
  "GET /health": { method: "GET", path: "/health", auth: false },
  "GET /health/ready": { method: "GET", path: "/health/ready", auth: false },
  "POST /auth/otp/request": { method: "POST", path: "/auth/otp/request", auth: false },
  "POST /auth/otp/verify": { method: "POST", path: "/auth/otp/verify", auth: false },
  "POST /auth/logout": { method: "POST", path: "/auth/logout", auth: false },
  "POST /auth/refresh": { method: "POST", path: "/auth/refresh", auth: false },
  "GET /me": { method: "GET", path: "/me", auth: true },
  "GET /users/me/profile": { method: "GET", path: "/users/me/profile", auth: true },
  "PATCH /users/me/profile": { method: "PATCH", path: "/users/me/profile", auth: true },
  "GET /listings": { method: "GET", path: "/listings", auth: false },
  "GET /listings/{id}": { method: "GET", path: "/listings/{id}", auth: false },
  "GET /listings/{id}/availability": { method: "GET", path: "/listings/{id}/availability", auth: false },
  "GET /me/bookings": { method: "GET", path: "/me/bookings", auth: true },
  "POST /bookings": { method: "POST", path: "/bookings", auth: true },
  "PATCH /bookings/{id}/reschedule": { method: "PATCH", path: "/bookings/{id}/reschedule", auth: true },
  "PATCH /bookings/{id}/cancel": { method: "PATCH", path: "/bookings/{id}/cancel", auth: true },
  "GET /me/app-state": { method: "GET", path: "/me/app-state", auth: true },
  "PATCH /me/app-state": { method: "PATCH", path: "/me/app-state", auth: true },
  "POST /notifications/push-subscriptions": { method: "POST", path: "/notifications/push-subscriptions", auth: true },
  "GET /me/notifications": { method: "GET", path: "/me/notifications", auth: true },
  "PATCH /me/notifications/{id}/read": { method: "PATCH", path: "/me/notifications/{id}/read", auth: true },
  "GET /me/saved-listings": { method: "GET", path: "/me/saved-listings", auth: true },
  "POST /me/saved-listings/{listingId}": { method: "POST", path: "/me/saved-listings/{listingId}", auth: true },
  "DELETE /me/saved-listings/{listingId}": { method: "DELETE", path: "/me/saved-listings/{listingId}", auth: true },
  "GET /conversations": { method: "GET", path: "/conversations", auth: true },
  "POST /conversations": { method: "POST", path: "/conversations", auth: true },
  "GET /conversations/{id}/messages": { method: "GET", path: "/conversations/{id}/messages", auth: true },
  "POST /conversations/{id}/messages": { method: "POST", path: "/conversations/{id}/messages", auth: true },
  "PATCH /conversations/{id}/read": { method: "PATCH", path: "/conversations/{id}/read", auth: true },
  "POST /payments/deposits": { method: "POST", path: "/payments/deposits", auth: true },
  "GET /payments/{id}": { method: "GET", path: "/payments/{id}", auth: true },
  "POST /payments/webhook": { method: "POST", path: "/payments/webhook", auth: false },
  "POST /contracts": { method: "POST", path: "/contracts", auth: true },
  "GET /contracts/{id}": { method: "GET", path: "/contracts/{id}", auth: true },
  "GET /owner/dashboard": { method: "GET", path: "/owner/dashboard", auth: true },
  "GET /owner/listings": { method: "GET", path: "/owner/listings", auth: true },
  "POST /owner/listings": { method: "POST", path: "/owner/listings", auth: true },
  "PATCH /owner/listings/{id}": { method: "PATCH", path: "/owner/listings/{id}", auth: true },
  "POST /owner/listings/{id}/images": { method: "POST", path: "/owner/listings/{id}/images", auth: true },
  "POST /owner/listings/{id}/images/upload-intent": { method: "POST", path: "/owner/listings/{id}/images/upload-intent", auth: true },
  "GET /owner/bookings": { method: "GET", path: "/owner/bookings", auth: true },
  "PATCH /owner/bookings/{id}/confirm": { method: "PATCH", path: "/owner/bookings/{id}/confirm", auth: true },
  "GET /admin/metrics": { method: "GET", path: "/admin/metrics", auth: true },
  "GET /admin/verifications": { method: "GET", path: "/admin/verifications", auth: true },
  "GET /admin/listings": { method: "GET", path: "/admin/listings", auth: true },
  "POST /admin/verifications/{id}/approve": { method: "POST", path: "/admin/verifications/{id}/approve", auth: true },
  "POST /admin/verifications/{id}/request-more": { method: "POST", path: "/admin/verifications/{id}/request-more", auth: true },
  "POST /admin/listings/{id}/review": { method: "POST", path: "/admin/listings/{id}/review", auth: true },
  "GET /admin/disputes": { method: "GET", path: "/admin/disputes", auth: true },
  "PATCH /admin/disputes/{id}": { method: "PATCH", path: "/admin/disputes/{id}", auth: true },
  "GET /admin/audit-logs": { method: "GET", path: "/admin/audit-logs", auth: true }
} as const satisfies Record<ApiOperationKey, { method: ApiMethod; path: string; auth: boolean }>;
